language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm run lint
  - npm test
after_success:
  - npm run semantic-release
branches:
  on:
    branch: master
