language: node_js
env:
  CODECLIMATE_REPO_TOKEN: 843c1e0702dbfd615b1074fc900ee514461e08442ce366cba37ea62f785a8369
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm run lint
  - npm run test-report
after_success:
  - npm run semantic-release
branches:
  on:
    branch: master
